### ISSUE TITLE
Updating this work?

### ISSUE THREAD

**Issue by kmoore134** [N-faycal/ZenPacks.iXsystems.TrueNAS#1]
Is there any chance of getting this work updated for later TrueNAS 9.10 series? If so, please contact me at kris@ixsystems.com to discuss details.

**Comment by N-faycal** [comment]
Hi Kris. Just pushed the new version rewritten to follow Zenoss ZenPack dev guidelines. It should work on the latest versions of FreeNAS as the older MIB implementation has been abandoned

**Comment by kmoore134** [comment]
Great!! Thanks for the update, we will let folks know on this side.

--
Kris Moore
Vice President of Engineering
iXsystems, Inc
Ph: (408) 943-4100
Ph: (408) 943-4101

Enterprise Storage & Servers Driven By Open Source

________________________________
